#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\ListCommand;

require __DIR__.'/vendor/autoload.php';

$application = new Application('txt2jira v2.0.0');
$application->add(new App\Commands\CommentCommand());
$application->add(new App\Commands\CommitCommand());
$application->add(new App\Commands\ConfigCommand());
$application->add(new App\Commands\CurrentCommand());
$application->add(new App\Commands\DeleteCommand());
$application->add(new App\Commands\EditCommand());
$application->add(new App\Commands\IssueCommand());
$application->add(new App\Commands\ListCommand());
$application->add(new App\Commands\StartCommand());
$application->add(new App\Commands\StopCommand());
$application->add((new ListCommand())->setName('commands'));
$application->setDefaultCommand('commands');
$application->run();
