#!/usr/bin/env php
<?php

use App\Config;
use App\ExecuteCommand;
use App\InitCommand;

require __DIR__.'/vendor/autoload.php';

try {

    $app = new Ahc\Cli\Application('txt2jira', 'v1.0.0');
    $app->add(new InitCommand(new Config()), 'i');
    $app->add(new ExecuteCommand(), 'c');
    $app->handle($_SERVER['argv']);

} catch (Exception $ex) {
    $interactor = new Ahc\Cli\IO\Interactor();
    $interactor->redBold($ex->getMessage(), true);
    exit(1);
}
